### ISSUE TITLE
Should we try to detect the value of `MACHINE` in `CMakeLists.txt`?

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/ssb-dbgen#48]
Valentin Grigoriev (@valco1994) suggests the use of CMake's platform-related macros (such as `WIN32` and `UNIX`) to auto-detect a correct value for the `MACHINE` preprocessor directive which the code uses.

**Comment by eyalroz** [comment]
So, pros and cons:

Pros:

* This seems to work for Windows, Linux and Mac OS
* No need to manually specify `MACHINE`, making it easier to build for non-savvy users.

Cons:

* What about all the other platforms?
* The "correct" approach is not to have a platform macro, but platform _features_ tested for, detected and the results placed in a generated `config.h` file. That was we don't even need to characterize a platform, just support for specific things. If we're trying to improve the build mechanism, why not just do that?

**Comment by valco1994** [comment]
I suppose that the feature-based approach is preferable, and if you are ready to implement it, I fully support your decision.

**Comment by eyalroz** [comment]
@valco1994 : If you can spare the time, I'd appreciate you looking at the drop_machine_spec branch, possibly pulling and building it to see everything's fine with it.

**Comment by valco1994** [comment]
Ok, I'll look at it

**Comment by eyalroz** [comment]
So, this discussion is resolved.
