### ISSUE TITLE
How to generate a lot of data without generating huge files

### ISSUE THREAD

**Issue by pofl** [eyalroz/ssb-dbgen#78]
I want to generate data with a very large scale factor. I want to process up to 1TB data in MariaDB but only have storage of 1TB. Is there a way to pipe generated data into the DB-specific import tool? Or can I use the -S option somehow? It sounds like it should be possible to generate x GB at a time, import it, and then generate the next x GB. Is that possible?

**Comment by eyalroz** [comment]
I haven't tried this myself, actually, but - what you need to do is choose a number of subsets of the data to use, with `-U`, then invoke `dbgen` with the update set index, i.e. invoke it with `-S 1`, then `-S2 2` etc.

Please try this to make sure it works...

**Comment by pofl** [comment]
Hi Eyal, thanks for replying!

Both `./dbgen -U 10 -S 1` and `./dbgen -U 10` create update files

```
-rw-r--r-- 1 pofl pofl 7.1K Dec 20 16:37 delete.1
-rw-r--r-- 1 pofl pofl 8.8K Dec 20 16:37 delete.10
-rw-r--r-- 1 pofl pofl 7.9K Dec 20 16:37 delete.2
-rw-r--r-- 1 pofl pofl 8.8K Dec 20 16:37 delete.3
-rw-r--r-- 1 pofl pofl 8.8K Dec 20 16:37 delete.4
-rw-r--r-- 1 pofl pofl 8.8K Dec 20 16:37 delete.5
-rw-r--r-- 1 pofl pofl 8.8K Dec 20 16:37 delete.6
-rw-r--r-- 1 pofl pofl 8.8K Dec 20 16:37 delete.7
-rw-r--r-- 1 pofl pofl 8.8K Dec 20 16:37 delete.8
-rw-r--r-- 1 pofl pofl 8.8K Dec 20 16:37 delete.9
-rw-r--r-- 1 pofl pofl 575K Dec 20 16:37 lineorder.tbl.u1
-rw-r--r-- 1 pofl pofl 597K Dec 20 16:37 lineorder.tbl.u10
-rw-r--r-- 1 pofl pofl 602K Dec 20 16:37 lineorder.tbl.u2
-rw-r--r-- 1 pofl pofl 582K Dec 20 16:37 lineorder.tbl.u3
-rw-r--r-- 1 pofl pofl 605K Dec 20 16:37 lineorder.tbl.u4
-rw-r--r-- 1 pofl pofl 592K Dec 20 16:37 lineorder.tbl.u5
-rw-r--r-- 1 pofl pofl 594K Dec 20 16:37 lineorder.tbl.u6
-rw-r--r-- 1 pofl pofl 583K Dec 20 16:37 lineorder.tbl.u7
-rw-r--r-- 1 pofl pofl 601K Dec 20 16:37 lineorder.tbl.u8
-rw-r--r-- 1 pofl pofl 598K Dec 20 16:37 lineorder.tbl.u9
```

If I run `./dbgen -S 1` after that the same .tbl files are generated like when I run the same cmd without the -S parameter.

**Comment by eyalroz** [comment]
I'll need to look into it. Please ping me again (here or by email) next week if I haven't.

**Comment by eyalroz** [comment]
So, this had us confused because of the problematic usage information - which has been (partially) fixed in TPC-H dbgen over the years, but not here. Now things should be clearer.

**Comment by pofl** [comment]
Thank you very much!
